### ISSUE TITLE
/usr/local/bin/zola: no such file or directory

### ISSUE THREAD

**Issue by Cloufish** [jauderho/dockerfiles#1933]
Any workaround from there? :/

```bash
[+] Running 1/0
 ✔ Container zola-web-1  Created                                                                                                                                        0.0s
Attaching to zola-web-1
zola-web-1  | exec /usr/local/bin/zola: no such file or directory
zola-web-1 exited with code 1
```

**Comment by jauderho** [comment]
This should be fixed now. Please try again.

**Comment by Cloufish** [comment]
Ok the problem was in IP Address bind to the WebApp.
It needs to be `0.0.0.0`

So having this `docker-compose.yml`:
```
version: '3.8'

services:
  web:
    image: j1mc/docker-zola:latest
    #image: jauderho/zola:latest
    volumes:
      -  ./blog_os/:/site
    ports:
      - 1111:1111
    command:
      - --root
      - ./site/blog
      - serve
      - --interface
      - 0.0.0.0
```

Solves the issue. 
Works great jauderho thank you!!! :)
